changes in ci to fasten the process 12

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -35,18 +35,20 @@ jobs:
       - uses: actions/checkout@v3
 
       - name: Increase Disk Space
-        run: |
-          echo "Expanding disk space"
-          df -h
+        run: df -h
 
       - name: Create AVD
         run: |
+          echo "Creating AVD..."
+          export ANDROID_SDK_ROOT=$ANDROID_HOME
+          mkdir -p ~/.android/avd
           echo "no" | avdmanager create avd --name test_avd --package "system-images;android-33;google_apis;x86_64" --abi x86_64 --device "pixel" --force
+          avdmanager list avd
 
       - name: Debug AVD
         run: |
-          avdmanager list avd
-          emulator -list-avds
+          ls -la ~/.android/avd
+          cat ~/.android/avd/test_avd.ini || echo "AVD config missing"
 
       - name: Start Emulator
         timeout-minutes: 10
